version: '3.8'

services:
  web:
    # image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    build: .
    container_name: flask-app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - IMAGE_TAG=${IMAGE_TAG}
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:

volumes:
  db-data:
# version: '3.8'

# services:
#   web-app:
#     build: .
#     container_name: entry-tracker-app
#     environment:
#       - DB_HOST=${DB_HOST}
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_NAME=${DB_NAME}
#     ports:
#       - '5000:5000'
#     depends_on:
#       mysql:
#         condition: service_healthy
#     networks:
#       - app_network

#   mysql:
#     image: mysql:5.7
#     container_name: mysql-db
#     environment:
#       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#       - MYSQL_DATABASE=${DB_NAME}
#     ports:
#       - '3306:3306'
#     networks:
#       - app_network
#     volumes:
#       - db-data:/var/lib/mysql
#     healthcheck:
#       test:
#         [
#           'CMD-SHELL',
#           'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1',
#         ]
#       interval: 10s
#       timeout: 5s
#       retries: 3
#       start_period: 20s
#   nginx:
#     image: nginx:alpine
#     ports:
#       - '80:80'
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web-app
#     networks:
#       - app_network

# networks:
#   app_network:

# volumes:
#   db-data:
# # version: '3.8'

# # services:
# #   web-app:
# #     build: .
# #     container_name: entry-tracker-app
# #     environment:
# #       - DB_HOST=${DB_HOST}
# #       - DB_USER=${DB_USER}
# #       - DB_PASSWORD=${DB_PASSWORD}
# #       - DB_NAME=${DB_NAME}
# #     ports:
# #       - '5000:5000'
# #     depends_on:
# #       mysql:
# #         condition: service_healthy
# #     networks:
# #       - app_network

# #   mysql:
# #     image: mysql:5.7
# #     container_name: mysql-db
# #     environment:
# #       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
# #       - MYSQL_DATABASE=${DB_NAME}
# #     ports:
# #       - '3306:3306'
# #     networks:
# #       - app_network
# #     volumes:
# #       - db-data:/var/lib/mysql
# #     healthcheck:
# #       test:
# #         [
# #           'CMD-SHELL',
# #           'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1',
# #         ]
# #       interval: 10s
# #       timeout: 5s
# #       retries: 3
# #       start_period: 20s
# #   nginx:
# #     image: nginx:alpine
# #     ports:
# #       - '80:80'
# #     volumes:
# #       - ./nginx.conf:/etc/nginx/nginx.conf
# #     depends_on:
# #       - web-app
# #     networks:
# #       - app_network

# # networks:
# #   app_network:

# # volumes:
# #   db-data:
