name: entrytracker cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #Run the application (outside of a container)
      - name: Run the application on port 5000 in the background
        run: |
          nohup python app.py &
      - name: Run tests
        run: |
          curl http://localhost:5000

      # install docker-compose
      - name: install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Package the application
      - name: Package the application into a Docker container
        run: docker build -t entry-tracker:latest .

        # Find the process using port 5000 and kill it
      - name: Kill the process using port 5000
        run: |
          sudo lsof -t -i:5000 | xargs kill -9

      - name: Run the application in the background
        run: |
          docker-compose up -d
      - name: Run curl tests
        run: |
          sleep 5
          curl http://localhost:5000

      # Push the artifact to AWS ECR registry

      # step 1: Configure AWS credentials
      - name: configure aws credentials
        run: aws configure set aws_access_key_id ${{ secrets.ECR_ACCESS_KEY }} && aws configure set aws_secret_access_key ${{ secrets.ECR_SECRET_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

      # step 2: Authenticate Docker to AWS ECR
      - name: Authenticate Docker to AWS ECR
        run: aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com

      # step 3: Tag Docker image
      # Tag Docker image
      - name: Tag Docker image
        run: docker tag entry-tracker:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/prod/entry-tracker:latest

      # step 4: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/prod/entry-tracker:latest

      - name: Deploy to EC2 and  Update the running container
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
          chmod 400 ${{ secrets.EC2_PRIVATE_KEY }}
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/prod/entry-tracker:latest
          docker-compose down
          docker-compose up -d

      #   run: |
      #     ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets. }}@${{ secrets.EC2_PUBLIC_IP }}
      #     chmod 400 ${{ secrets.EC2_PRIVATE_KEY }}
      #     docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/prod/entry-tracker:latest
      # - name: Update the running container
      #   run: |
      #     docker-compose down
      #     docker-compose up -d
