name: entrytracker cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #Run the application (outside of a container)
      - name: Run the application on port 5000 in the background
        run: |
          nohup python app.py &
      - name: Run tests
        run: |
          curl http://localhost:5000

      # install docker-compose
      - name: install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Package the application
      - name: Package the application into a Docker container
        run: docker build -t entrytracker:latest .

        # Find the process using port 5000 and kill it
      - name: Kill the process using port 5000
        run: |
          sudo lsof -t -i:5000 | xargs kill -9

      - name: Run the application in a container
        run: docker run -d -p 5000:5000 entrytracker:latest
      - name: Run tests
        run: |
          sleep 5
          curl http://localhost:5000
      # # Find the process using port 5000 and kill it
      # - name: Kill the process using port 5000
      #   run: |
      #     sudo lsof -t -i:5000 | xargs kill -9
      # - name: install docker-compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose
      # - name: Docker Compose Setup
      #   run: |
      #     docker-compose up -d
      # - name: Run curl tests
      #   run: |
      #     sleep 5
      #     curl http://localhost:5000
